# Generated by Django 4.1 on 2023-07-05 17:12

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_video_text_image_file_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="text",
            name="content",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
